"""Live BTC price polling.

Primary feed: Binance/Coinbase spot ticker (fast, public, no auth) — reused
retry/backoff pattern from the existing btc_session_candles.py/ny_open_btc_candle.py
scripts in Downloads.

**What settlement actually measures.** Read verbatim from a live market's Gamma
`description` field (btc-updown-5m-1789122300, 2026-09-11):

    "This market will resolve to "Up" if the time-weighted average price (TWAP)
    of Bitcoin, generated by Chainlink, of the time range specified in the title
    is greater than or equal to the price at the beginning of that range."
    Source: the BTC/USD TWAP data stream at
    https://data.chain.link/streams/btc-usd-twap-60s-streams

Two consequences that drive the design of this module and quant_signal.py:

1. The comparison is **TWAP-over-the-window vs. the price at window start** —
   not close vs. open. The average of the path, not its endpoint. So the series
   this desk models has to be integrated over the window, and the reference is
   the settlement series' value at the boundary.
2. The source is a Chainlink **Data Stream** (`btc-usd-twap-60s`), which is a
   different product from the on-chain aggregator read by
   fetch_chainlink_btcusd() below — Data Streams are off-chain and pull-based
   and need Chainlink API credentials we don't have. The stream is itself a
   trailing 60-second TWAP, so settlement is a TWAP of a TWAP.

We therefore can't read the settlement series directly. What we can do is model
the same functional form (TWAP_LOOKBACK-second trailing average, integrated over
the window) on top of spot, which is highly correlated with Chainlink's BTC/USD
aggregate over 5-minute horizons. The residual basis is the known, unhedged risk
here. The on-chain aggregator is a level sanity-check only — it is NOT the
settlement feed, and it updates on a deviation/heartbeat trigger, so it can be
minutes stale.
"""
import json
import math
import time
import urllib.error
import urllib.request

import config

_web3 = None
_chainlink_feed = None

# Minimal ABI: only the one function we need.
_AGGREGATOR_ABI = [
    {
        "inputs": [],
        "name": "latestRoundData",
        "outputs": [
            {"name": "roundId", "type": "uint80"},
            {"name": "answer", "type": "int256"},
            {"name": "startedAt", "type": "uint256"},
            {"name": "updatedAt", "type": "uint256"},
            {"name": "answeredInRound", "type": "uint80"},
        ],
        "stateMutability": "view",
        "type": "function",
    }
]


def http_json(url, retries=3, timeout=10):
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "btcbot/1.0"})
            with urllib.request.urlopen(req, timeout=timeout) as r:
                return json.loads(r.read().decode())
        except urllib.error.HTTPError as e:
            if e.code in (418, 429) and attempt < retries - 1:
                time.sleep(2 ** attempt)
                continue
            raise
        except urllib.error.URLError:
            if attempt < retries - 1:
                time.sleep(1 + attempt)
                continue
            raise
    return None


def fetch_binance_price(symbol: str = "BTCUSDT") -> float:
    data = http_json(f"https://api.binance.com/api/v3/ticker/price?symbol={symbol}")
    return float(data["price"])


def fetch_coinbase_price(symbol: str = "BTC-USD") -> float:
    data = http_json(f"https://api.exchange.coinbase.com/products/{symbol}/ticker")
    return float(data["price"])


def fetch_spot_price() -> float:
    """Best-effort spot price: Binance first, Coinbase as fallback."""
    try:
        return fetch_binance_price()
    except Exception:
        return fetch_coinbase_price()


def fetch_chainlink_btcusd() -> tuple[float, int]:
    """Read the on-chain Chainlink BTC/USD feed used for settlement. Read-only,
    no gas. Returns (price_usd, updated_at_epoch_seconds) — the timestamp matters
    because this feed only updates on a deviation/heartbeat trigger, so a "live"
    read can legitimately be minutes stale, which is most of a 5-minute window."""
    global _web3, _chainlink_feed
    if _chainlink_feed is None:
        from web3 import Web3

        _web3 = Web3(Web3.HTTPProvider(config.POLYGON_RPC_URL))
        _chainlink_feed = _web3.eth.contract(
            address=Web3.to_checksum_address(config.CHAINLINK_BTCUSD_FEED_ADDRESS),
            abi=_AGGREGATOR_ABI,
        )
    _, answer, _, updated_at, _ = _chainlink_feed.functions.latestRoundData().call()
    return answer / 1e8, updated_at


def _interpolate(samples: list[tuple[float, float]], ts: float) -> float | None:
    """Value at `ts` by linear interpolation between the bracketing samples.
    None if `ts` falls outside the sampled span — the caller must not silently
    extrapolate a reference price it never observed."""
    if not samples or ts < samples[0][0] or ts > samples[-1][0]:
        return None
    for (t0, p0), (t1, p1) in zip(samples, samples[1:]):
        if t0 <= ts <= t1:
            if t1 == t0:
                return p1
            return p0 + (p1 - p0) * (ts - t0) / (t1 - t0)
    return samples[-1][1]


def trapezoid_integral(points: list[tuple[float, float]]) -> float:
    """∫ value dt over the span of `points`, treating the series as piecewise
    linear between samples."""
    return sum(
        (t1 - t0) * (v0 + v1) / 2.0
        for (t0, v0), (t1, v1) in zip(points, points[1:])
    )


class RollingPriceTracker:
    """In-process buffer of (timestamp, price) samples spanning the pre-roll plus
    the current window. Provides the two primitives the settlement model needs: a
    trailing time-weighted average (matching the shape of the Chainlink
    TWAP-60s stream that settles these markets) and a diffusion-rate estimate."""

    def __init__(self):
        self.samples: list[tuple[float, float]] = []

    def reset(self):
        self.samples.clear()

    def add(self, price: float, ts: float | None = None):
        self.samples.append((ts if ts is not None else time.time(), price))

    def open_price(self) -> float | None:
        return self.samples[0][1] if self.samples else None

    def last_price(self) -> float | None:
        return self.samples[-1][1] if self.samples else None

    def last_ts(self) -> float | None:
        return self.samples[-1][0] if self.samples else None

    def twap_at(self, ts: float, lookback_seconds: float) -> tuple[float | None, float]:
        """Trailing time-weighted average price over [ts - lookback, ts].

        Returns (twap, covered_seconds). `covered_seconds` is how much of the
        requested lookback we actually have samples for — the caller decides
        whether partial coverage is good enough, because at the window boundary
        it's the difference between a real settlement reference and a guess.
        """
        start = ts - lookback_seconds
        points = [(t, p) for t, p in self.samples if start < t < ts]

        left = _interpolate(self.samples, start)
        if left is not None:
            points.insert(0, (start, left))
        right = _interpolate(self.samples, ts)
        if right is not None:
            points.append((ts, right))

        if not points:
            return None, 0.0
        if len(points) == 1:
            return points[0][1], 0.0

        covered = points[-1][0] - points[0][0]
        if covered <= 0:
            return points[-1][1], 0.0
        return trapezoid_integral(points) / covered, covered

    def momentum_bps(self) -> float:
        """Price change from the earliest sample to the latest, in bps. Note this
        spans the pre-roll as well as the window, so it is NOT the window's
        deviation from its open — quant_signal computes that against the
        settlement reference instead."""
        if len(self.samples) < 2:
            return 0.0
        o, c = self.samples[0][1], self.samples[-1][1]
        return (c - o) / o * 10_000

    def realized_vol_bps(self) -> float:
        """Simple realized volatility proxy: mean absolute tick-to-tick move in bps."""
        if len(self.samples) < 3:
            return 0.0
        moves = []
        for (_, p0), (_, p1) in zip(self.samples, self.samples[1:]):
            moves.append(abs(p1 - p0) / p0 * 10_000)
        return sum(moves) / len(moves)

    def sigma_bps_per_sqrt_second(self) -> float:
        """Diffusion rate σ in bps per √second, from tick-to-tick moves.

        Two corrections over using realized_vol_bps() directly as a stdev:

        * A mean *absolute* move is not a standard deviation. For a mean-zero
          normal, E|X| = σ√(2/π) ≈ 0.798σ, so treating the mean absolute move as
          σ understates the real diffusion by ~20% — which pushes every
          probability further from 0.5 and is one of the mechanical sources of
          the overconfidence the 2026-09-10 review measured.
        * Each interval is normalised by its own √dt before averaging, because
          the tick cadence deliberately changes mid-window (FAST_TICK_SECONDS ->
          SLOW_TICK_SECONDS) and σ scales with √dt.
        """
        if len(self.samples) < 3:
            return 0.0
        rates = []
        for (t0, p0), (t1, p1) in zip(self.samples, self.samples[1:]):
            dt = t1 - t0
            if dt <= 0 or p0 <= 0:
                continue
            move_bps = abs(p1 - p0) / p0 * 10_000
            rates.append(move_bps / math.sqrt(2.0 / math.pi) / math.sqrt(dt))
        if not rates:
            return 0.0
        return sum(rates) / len(rates)
